### ISSUE TITLE
Can't compile with OS X and SDK 0.4.4

### ISSUE THREAD

**Issue by jmtatsch** [OTL/oculus#10]
Is this package compatible with SDK 0.4.4?

`In file included from /Users/tatsch/ros_catkin_ws/src/oculus/oculus_driver/src/oculus_ros.cpp:1:
/Users/tatsch/ros_catkin_ws/src/oculus/oculus_driver/include/oculus_driver/oculus_ros.h:23:27: error: no member named 'DeviceManager' in namespace 'OVR'
            OVR::Ptr<OVR::DeviceManager> manager;
                     ~~~~~^
/Users/tatsch/ros_catkin_ws/src/oculus/oculus_driver/include/oculus_driver/oculus_ros.h:24:27: error: no member named 'HMDDevice' in namespace 'OVR'
            OVR::Ptr<OVR::HMDDevice> hmd;
                     ~~~~~^
/Users/tatsch/ros_catkin_ws/src/oculus/oculus_driver/include/oculus_driver/oculus_ros.h:25:27: error: no member named 'SensorDevice' in namespace 'OVR'
            OVR::Ptr<OVR::SensorDevice> sensor;
                     ~~~~~^
/Users/tatsch/ros_catkin_ws/src/oculus/oculus_driver/include/oculus_driver/oculus_ros.h:26:18: error: no type named 'SensorFusion' in namespace 'OVR'
            OVR::SensorFusion* fusion_result;
            ~~~~~^
/Users/tatsch/ros_catkin_ws/src/oculus/oculus_driver/include/oculus_driver/oculus_ros.h:27:18: error: no type named 'HMDInfo' in namespace 'OVR'
            OVR::HMDInfo info;
            ~~~~~^`

**Comment by OTL** [comment]
I think this package is very old. I mean this may be not compatible with 0.4.4.

**Comment by jmtatsch** [comment]
I managed to build the node with the  0.2.5 sdk.

First I had to rebuild libovr :

```
xcrun xcodebuild -target ovr -configuration Debug GCC_ENABLE_CPP_RTTI=YES  GCC_ENABLE_CPP_EXCEPTIONS=YES
```

and add the lines :

```
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -frtti -fexceptions" )
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -frtti -fexceptions")
```

to oculus_driver/CMakeLists.txt
Maybe that is helpful for other people. Still it would be nice if support for the latest SDK could be added...

**Comment by jmtatsch** [comment]
Unfortunately the 0.2.5 SDK is incompatible with Oculus DK2
